package Telas;

import com.amazonaws.services.rekognition.model.CreateCollectionResult;
import com.amazonaws.services.rekognition.model.DeleteCollectionResult;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controle.Comunicaçao;
import org.json.JSONArray;
import org.json.JSONException;

/**
 *
 * @author Julio
 */
public class Principal extends javax.swing.JFrame {

    Comunicaçao conexao = new Comunicaçao();
    String nomeDoAlbum;

    public Principal() {
        initComponents();
        this.setTitle("Tela Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        btnCriarAlbum = new javax.swing.JButton();
        btnVerAlbum = new javax.swing.JButton();
        btnExcluirAlbum = new javax.swing.JButton();
        BtnListarFaces = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnEnviarImagem = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblArmazenamento = new javax.swing.JLabel();
        lblPasta = new javax.swing.JLabel();
        btnEnviarParaAlbum = new javax.swing.JButton();
        btnVerImagens = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnCompararFaces = new javax.swing.JButton();
        lblFunçoesPrincipais = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Reconhecimento Facial");

        lblSubTitulo.setText("Escolha uma Opção");

        btnCriarAlbum.setText("Criar Album");
        btnCriarAlbum.setToolTipText("Cria um album");
        btnCriarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAlbumActionPerformed(evt);
            }
        });

        btnVerAlbum.setText("Ver Albuns");
        btnVerAlbum.setToolTipText("Retorna todos albuns existentes.");
        btnVerAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlbumActionPerformed(evt);
            }
        });

        btnExcluirAlbum.setText("Excluir album");
        btnExcluirAlbum.setToolTipText("Exclui um album.");
        btnExcluirAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAlbumActionPerformed(evt);
            }
        });

        BtnListarFaces.setText("Listar Faces");
        BtnListarFaces.setToolTipText("Lista Faces cadastradas em um album.");
        BtnListarFaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarFacesActionPerformed(evt);
            }
        });

        btnEnviarImagem.setText("Enviar imagem");
        btnEnviarImagem.setToolTipText("Envia uma imagem ao bucket.");
        btnEnviarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarImagemActionPerformed(evt);
            }
        });

        lblArmazenamento.setText("Opções de armazenamento");

        lblPasta.setText("Opções de pasta");

        btnEnviarParaAlbum.setText("Enviar Imagem para album");
        btnEnviarParaAlbum.setToolTipText("Envia uma imagem para um album.");
        btnEnviarParaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarParaAlbumActionPerformed(evt);
            }
        });

        btnVerImagens.setText("Ver Imagens");
        btnVerImagens.setToolTipText("Visualiza imagens hospedadas no BD.");
        btnVerImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerImagensActionPerformed(evt);
            }
        });

        btnCompararFaces.setText("Comparar Faces");
        btnCompararFaces.setToolTipText("Reconhece uma face em uma foto.");
        btnCompararFaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararFacesActionPerformed(evt);
            }
        });

        lblFunçoesPrincipais.setText("Funções principais");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnEnviarImagem)
                        .addGap(114, 114, 114)
                        .addComponent(btnVerImagens))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnEnviarParaAlbum)
                        .addGap(61, 61, 61)
                        .addComponent(btnCompararFaces))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblSubTitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnCriarAlbum)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerAlbum)
                        .addGap(34, 34, 34)
                        .addComponent(btnExcluirAlbum)
                        .addGap(29, 29, 29)
                        .addComponent(BtnListarFaces))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblPasta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblArmazenamento))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblFunçoesPrincipais)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArmazenamento)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarImagem)
                    .addComponent(btnVerImagens))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPasta)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarAlbum)
                    .addComponent(btnVerAlbum)
                    .addComponent(btnExcluirAlbum)
                    .addComponent(BtnListarFaces))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFunçoesPrincipais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompararFaces)
                    .addComponent(btnEnviarParaAlbum))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(568, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAlbumActionPerformed

            //Cria Album AWS Rekognition
        try {
            JFrame frame = new JFrame();
            nomeDoAlbum = JOptionPane.showInputDialog(frame, "Digite o nome do album ?","Criar Album",1);
           if(nomeDoAlbum!=null){
                      
                CreateCollectionResult criarPasta = conexao.criarPasta(nomeDoAlbum);
                 if (criarPasta.getStatusCode().equals(200)) { //Codigo 200 é retornado quando a solicitação foi bem sucedida.
                    JOptionPane.showMessageDialog(null,"Pasta "+nomeDoAlbum+" criada" );
                }
            }
             

        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCriarAlbumActionPerformed

    private void btnVerAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlbumActionPerformed

        try {
            //ver todos os albums. AWS
            JSONArray resposta = conexao.listarPasta();

            Retorno tela = new Retorno(resposta,3); //o primeiro parametro é a resposta retornada e o id que no caso é 3 pois é da função de escrever os albuns.
            tela.show();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnVerAlbumActionPerformed

    private void btnExcluirAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAlbumActionPerformed
        JFrame frame = new JFrame();
        nomeDoAlbum = JOptionPane.showInputDialog(frame, "Digite o nome do album a excluir?","Excluir Album",1);  //Abre uma janela pedindo o nome do album a excluir, e atribui a uma variavel.
           if(nomeDoAlbum!=null) {
                    DeleteCollectionResult excluirPasta = conexao.excluirPasta(nomeDoAlbum);    //Chama a funçao para excluir a pasta, passando o nome da pasta a ser excluida.
                    if (excluirPasta.getStatusCode().equals(200)) { //Codigo 200 é retornado quando a solicitação foi bem sucedida.
                        JOptionPane.showMessageDialog(null, "Pasta "+nomeDoAlbum+" excluída");
                        }
                }
    }//GEN-LAST:event_btnExcluirAlbumActionPerformed

    private void BtnListarFacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarFacesActionPerformed
        try {
            JFrame frame = new JFrame();
            nomeDoAlbum = JOptionPane.showInputDialog(frame, "Digite o nome do album a listar?");
            
            if(nomeDoAlbum.equals("''") || nomeDoAlbum.equals(" ") || nomeDoAlbum.equals("")){ //verifica se o campo foi preenchido.
            JOptionPane.showMessageDialog(null, "Não é possivel encontrar album com nome vazio");
            }
            else{
            JSONArray resposta = conexao.listarFaces(nomeDoAlbum);
            
            Retorno tela = new Retorno(resposta,1); //o primeiro parametro é a resposta retornada e o id que no caso é 1 pois é da função de escrever as faces.
            tela.show();
            }
           
        } catch (JsonProcessingException ex) {
             JOptionPane.showMessageDialog(null, "ERRO : "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) { 
            JOptionPane.showMessageDialog(null, "ERRO : "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnListarFacesActionPerformed

    private void btnEnviarParaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarParaAlbumActionPerformed
        InserirImagem tela = new InserirImagem();
        tela.show();


    }//GEN-LAST:event_btnEnviarParaAlbumActionPerformed

    private void btnEnviarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarImagemActionPerformed
        Upload tela = new Upload();
        tela.show();
    }//GEN-LAST:event_btnEnviarImagemActionPerformed

    private void btnVerImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerImagensActionPerformed
        Comunicaçao conexao = new Comunicaçao();
        JSONArray resposta;
        try {
            resposta = conexao.listarItens(); //chama a funçao listar itens, que retorna as fotos que estao na bucket.
            
            Retorno tela = new Retorno(resposta,2);//o primeiro parametro é a resposta retornada e o id que no caso é 2 pois é da função de escrever os itens.
            tela.show();
        } catch (JSONException ex) {
             JOptionPane.showMessageDialog(null, "ERRO : "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerImagensActionPerformed

    private void btnCompararFacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararFacesActionPerformed
        ReconhecerRosto tela = new ReconhecerRosto();
        tela.show();
    }//GEN-LAST:event_btnCompararFacesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListarFaces;
    private javax.swing.JButton btnCompararFaces;
    private javax.swing.JButton btnCriarAlbum;
    private javax.swing.JButton btnEnviarImagem;
    private javax.swing.JButton btnEnviarParaAlbum;
    private javax.swing.JButton btnExcluirAlbum;
    private javax.swing.JButton btnVerAlbum;
    private javax.swing.JButton btnVerImagens;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblArmazenamento;
    private javax.swing.JLabel lblFunçoesPrincipais;
    private javax.swing.JLabel lblPasta;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
