/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import com.amazonaws.services.rekognition.model.FaceMatch;
import com.amazonaws.services.rekognition.model.SearchFacesResult;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import Controle.Comunicaçao;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONException;

/**
 *
 * @author Julio
 */
public class ReconhecerRosto extends javax.swing.JFrame {

    /**
     * Creates new form ReconhecerRosto
     */
    public ReconhecerRosto() {
        initComponents();
        this.setTitle("Reconhecer Face");
        try {
            preencherFotos();
            
        } catch (JSONException ex) {
            Logger.getLogger(InserirImagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblImagemanalisada = new javax.swing.JLabel();
        txtImagemAnalisada = new javax.swing.JTextField();
        lblPastaPesquisada = new javax.swing.JLabel();
        txtPastaPesquisada = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblInformacao = new javax.swing.JLabel();
        txtImagensBucket = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Reconhecer Face");

        lblSubTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSubTitulo.setText("Imagens Disponiveis na Bucket");

        lblImagemanalisada.setText("Imagem Analisada:");

        lblPastaPesquisada.setText("Pasta:");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblInformacao.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblInformacao.setText("*Veja abaixo as fotos que estão disponiveis no repositorio.");

        txtImagensBucket.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEnviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpar))
                            .addComponent(lblSubTitulo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(txtImagensBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblImagemanalisada)
                                .addGap(18, 18, 18)
                                .addComponent(txtImagemAnalisada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addComponent(lblPastaPesquisada)
                        .addGap(18, 18, 18)
                        .addComponent(txtPastaPesquisada, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagemanalisada)
                    .addComponent(lblPastaPesquisada)
                    .addComponent(txtImagemAnalisada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPastaPesquisada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblInformacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnLimpar))
                .addGap(29, 29, 29)
                .addComponent(lblSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtImagensBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(580, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
      
            Comunicaçao comunicaçao = new Comunicaçao();
            SearchFacesResult searchFacesByImageResult = comunicaçao.procurarFaces(txtPastaPesquisada.getText(), txtImagemAnalisada.getText());
            List< FaceMatch> faceImageMatches = searchFacesByImageResult.getFaceMatches();
            
            for (FaceMatch face : faceImageMatches) {
                JOptionPane.showMessageDialog(null, "A face analisada é semelhante a " + face.getFace().getExternalImageId() + " Porcentagem de chance " + face.getFace().getConfidence() + "%");
                }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtImagemAnalisada.setText(""); //Limpa o campo ImagemAnalisada
        txtPastaPesquisada.setText(""); //Limpa o campo Pasta a ser pesquisada.
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagemanalisada;
    private javax.swing.JLabel lblInformacao;
    private javax.swing.JLabel lblPastaPesquisada;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtImagemAnalisada;
    private java.awt.TextArea txtImagensBucket;
    private javax.swing.JTextField txtPastaPesquisada;
    // End of variables declaration//GEN-END:variables

    public void preencherFotos() throws JSONException{ //funçao para preencher area de texto, com os itens do bucker.
           Comunicaçao conexao = new Comunicaçao();     
           JSONArray resposta = conexao.listarItens();   //chama a funçao listar itens, que retorna as fotos que estao na bucket.

           for (int i = 0; i < resposta.length(); i++) {
           //Escreve numa JtextArea, as imagens que estão na Bucket.
           txtImagensBucket.append(" Nome:  "+resposta.getJSONObject(i).getString("Nome")+"  ; Tamanho:"+resposta.getJSONObject(i).getInt("Tamanho")+"\n");
           }
        }
}
